services:
  rails:
    command: /bin/sh -c "while sleep 1000; do :; done"
    build: .
    volumes:
      - rails_bundle:/workspaces/.bundle
    ports:
      - 3000:3000
    env_file:
      - ./.user.env
    environment:
      RAILS_ENV: development
      TZ: "Asia/Tokyo"
      BUNDLE_APP_CONFIG: /workspaces/.bundle
  railsdb:
    image: postgres:13
    environment:
      POSTGRES_DATABASE: railsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@55w0rd
    volumes:
      - rails_db:/workspaces/.data
volumes:
  rails_bundle:
  rails_db:
